// constants/index.ts

export const interviewCovers = [
  "/covers/adobe.png",
  "/covers/amazon.png",
  "/covers/facebook.png",
  "/covers/hostinger.png",
  "/covers/pinterest.png",
  "/covers/quora.png",
  "/covers/reddit.png",
  "/covers/telegram.png",
  "/covers/tiktok.png",
  "/covers/yahoo.png"
];

export const mappings: Record<string, string> = {
  "react": "react",
  "reactjs": "react",
  "vue": "vue",
  "vuejs": "vue",
  "angular": "angular",
  "angularjs": "angular",
  "node": "nodejs",
  "nodejs": "nodejs",
  "express": "express",
  "expressjs": "express",
  "javascript": "javascript",
  "js": "javascript",
  "typescript": "typescript",
  "ts": "typescript",
  "python": "python",
  "py": "python",
  "java": "java",
  "c++": "cplusplus",
  "cpp": "cplusplus",
  "c#": "csharp",
  "csharp": "csharp",
  "php": "php",
  "html": "html5",
  "html5": "html5",
  "css": "css3",
  "css3": "css3",
  "tailwind": "tailwindcss",
  "tailwindcss": "tailwindcss",
  "bootstrap": "bootstrap",
  "mongodb": "mongodb",
  "mongo": "mongodb",
  "mysql": "mysql",
  "postgresql": "postgresql",
  "postgres": "postgresql",
  "sql": "sql",
  "firebase": "firebase",
  "docker": "docker",
  "kubernetes": "kubernetes",
  "k8s": "kubernetes",
  "aws": "amazonwebservices",
  "amazon": "amazonwebservices",
  "azure": "azure",
  "gcp": "googlecloud",
  "google cloud": "googlecloud",
  "git": "git",
  "github": "github",
  "linux": "linux",
  "ubuntu": "ubuntu"
};