// lib/config/currency.ts

export interface CountryCurrency {
  code: string;
  symbol: string;
  name: string;
  locale: string;
  position: 'before' | 'after';
  decimalPlaces: number;
}

// Default fallback
export const DEFAULT_COUNTRY = 'kenya';
export const DEFAULT_CURRENCY: CountryCurrency = {
  code: 'KES',
  symbol: 'Ksh',
  name: 'Kenyan Shilling',
  locale: 'sw-KE',
  position: 'before',
  decimalPlaces: 2,
};

// ==================== COMPLETE COUNTRY CURRENCY MAP ====================
export const COUNTRY_CURRENCY_MAP: Record<string, CountryCurrency> = {
  // ==================== SWAHILI-SPEAKING COUNTRIES ====================
  kenya: {
    code: 'KES',
    symbol: 'Ksh',
    name: 'Kenyan Shilling',
    locale: 'sw-KE',
    position: 'before',
    decimalPlaces: 2,
  },
  tanzania: {
    code: 'TZS',
    symbol: 'TSh',
    name: 'Tanzanian Shilling',
    locale: 'sw-TZ',
    position: 'before',
    decimalPlaces: 2,
  },
  uganda: {
    code: 'UGX',
    symbol: 'USh',
    name: 'Ugandan Shilling',
    locale: 'sw-UG',
    position: 'before',
    decimalPlaces: 2,
  },
  rwanda: {
    code: 'RWF',
    symbol: 'FRw',
    name: 'Rwandan Franc',
    locale: 'rw-RW',
    position: 'before',
    decimalPlaces: 2,
  },
  burundi: {
    code: 'BIF',
    symbol: 'FBu',
    name: 'Burundian Franc',
    locale: 'rn-BI',
    position: 'before',
    decimalPlaces: 2,
  },
  somalia: {
    code: 'SOS',
    symbol: 'SOS',
    name: 'Somali Shilling',
    locale: 'so-SO',
    position: 'before',
    decimalPlaces: 2,
  },
  'congo drc': {
    code: 'CDF',
    symbol: 'FC',
    name: 'Congolese Franc',
    locale: 'sw-CD',
    position: 'before',
    decimalPlaces: 2,
  },
  comoros: {
    code: 'KMF',
    symbol: 'CF',
    name: 'Comorian Franc',
    locale: 'sw-KM',
    position: 'before',
    decimalPlaces: 2,
  },

  // ==================== ENGLISH-SPEAKING COUNTRIES ====================
  // Africa
  nigeria: {
    code: 'NGN',
    symbol: '₦',
    name: 'Nigerian Naira',
    locale: 'en-NG',
    position: 'before',
    decimalPlaces: 2,
  },
  ghana: {
    code: 'GHS',
    symbol: 'GH₵',
    name: 'Ghanaian Cedi',
    locale: 'en-GH',
    position: 'before',
    decimalPlaces: 2,
  },
  'south africa': {
    code: 'ZAR',
    symbol: 'R',
    name: 'South African Rand',
    locale: 'en-ZA',
    position: 'before',
    decimalPlaces: 2,
  },
  zambia: {
    code: 'ZMW',
    symbol: 'ZK',
    name: 'Zambian Kwacha',
    locale: 'en-ZM',
    position: 'before',
    decimalPlaces: 2,
  },
  malawi: {
    code: 'MWK',
    symbol: 'MK',
    name: 'Malawian Kwacha',
    locale: 'en-MW',
    position: 'before',
    decimalPlaces: 2,
  },
  botswana: {
    code: 'BWP',
    symbol: 'P',
    name: 'Botswana Pula',
    locale: 'en-BW',
    position: 'before',
    decimalPlaces: 2,
  },
  zimbabwe: {
    code: 'USD',
    symbol: '$',
    name: 'US Dollar',
    locale: 'en-ZW',
    position: 'before',
    decimalPlaces: 2,
  },
  eswatini: {
    code: 'SZL',
    symbol: 'L',
    name: 'Swazi Lilangeni',
    locale: 'en-SZ',
    position: 'before',
    decimalPlaces: 2,
  },
  lesotho: {
    code: 'LSL',
    symbol: 'L',
    name: 'Lesotho Loti',
    locale: 'en-LS',
    position: 'before',
    decimalPlaces: 2,
  },
  namibia: {
    code: 'NAD',
    symbol: '$',
    name: 'Namibian Dollar',
    locale: 'en-NA',
    position: 'before',
    decimalPlaces: 2,
  },
  mozambique: {
    code: 'MZN',
    symbol: 'MT',
    name: 'Mozambican Metical',
    locale: 'pt-MZ',
    position: 'before',
    decimalPlaces: 2,
  },
  angola: {
    code: 'AOA',
    symbol: 'Kz',
    name: 'Angolan Kwanza',
    locale: 'pt-AO',
    position: 'before',
    decimalPlaces: 2,
  },
  sudan: {
    code: 'SDG',
    symbol: '£SD',
    name: 'Sudanese Pound',
    locale: 'ar-SD',
    position: 'before',
    decimalPlaces: 2,
  },
  'south sudan': {
    code: 'SSP',
    symbol: '£SS',
    name: 'South Sudanese Pound',
    locale: 'en-SS',
    position: 'before',
    decimalPlaces: 2,
  },
  'sierra leone': {
    code: 'SLL',
    symbol: 'Le',
    name: 'Sierra Leonean Leone',
    locale: 'en-SL',
    position: 'before',
    decimalPlaces: 2,
  },
  liberia: {
    code: 'LRD',
    symbol: '$',
    name: 'Liberian Dollar',
    locale: 'en-LR',
    position: 'before',
    decimalPlaces: 2,
  },
  gambia: {
    code: 'GMD',
    symbol: 'D',
    name: 'Gambian Dalasi',
    locale: 'en-GM',
    position: 'before',
    decimalPlaces: 2,
  },
  seychelles: {
    code: 'SCR',
    symbol: '₨',
    name: 'Seychellois Rupee',
    locale: 'en-SC',
    position: 'before',
    decimalPlaces: 2,
  },
  mauritius: {
    code: 'MUR',
    symbol: '₨',
    name: 'Mauritian Rupee',
    locale: 'en-MU',
    position: 'before',
    decimalPlaces: 2,
  },

  // North America / Caribbean
  'united states': {
    code: 'USD',
    symbol: '$',
    name: 'US Dollar',
    locale: 'en-US',
    position: 'before',
    decimalPlaces: 2,
  },
  canada: {
    code: 'CAD',
    symbol: 'C$',
    name: 'Canadian Dollar',
    locale: 'en-CA',
    position: 'before',
    decimalPlaces: 2,
  },
  jamaica: {
    code: 'JMD',
    symbol: '$',
    name: 'Jamaican Dollar',
    locale: 'en-JM',
    position: 'before',
    decimalPlaces: 2,
  },
  'trinidad and tobago': {
    code: 'TTD',
    symbol: 'TT$',
    name: 'Trinidadian Dollar',
    locale: 'en-TT',
    position: 'before',
    decimalPlaces: 2,
  },
  barbados: {
    code: 'BBD',
    symbol: '$',
    name: 'Barbadian Dollar',
    locale: 'en-BB',
    position: 'before',
    decimalPlaces: 2,
  },
  bahamas: {
    code: 'BSD',
    symbol: '$',
    name: 'Bahamian Dollar',
    locale: 'en-BS',
    position: 'before',
    decimalPlaces: 2,
  },
  belize: {
    code: 'BZD',
    symbol: '$',
    name: 'Belize Dollar',
    locale: 'en-BZ',
    position: 'before',
    decimalPlaces: 2,
  },
  guyana: {
    code: 'GYD',
    symbol: '$',
    name: 'Guyanese Dollar',
    locale: 'en-GY',
    position: 'before',
    decimalPlaces: 2,
  },
  suriname: {
    code: 'SRD',
    symbol: '$',
    name: 'Surinamese Dollar',
    locale: 'en-SR',
    position: 'before',
    decimalPlaces: 2,
  },

  // Oceania
  australia: {
    code: 'AUD',
    symbol: 'A$',
    name: 'Australian Dollar',
    locale: 'en-AU',
    position: 'before',
    decimalPlaces: 2,
  },
  'new zealand': {
    code: 'NZD',
    symbol: 'NZ$',
    name: 'New Zealand Dollar',
    locale: 'en-NZ',
    position: 'before',
    decimalPlaces: 2,
  },
  fiji: {
    code: 'FJD',
    symbol: 'FJ$',
    name: 'Fijian Dollar',
    locale: 'en-FJ',
    position: 'before',
    decimalPlaces: 2,
  },
  'papua new guinea': {
    code: 'PGK',
    symbol: 'K',
    name: 'Kina',
    locale: 'en-PG',
    position: 'before',
    decimalPlaces: 2,
  },

  // Asia (English-speaking)
  india: {
    code: 'INR',
    symbol: '₹',
    name: 'Indian Rupee',
    locale: 'en-IN',
    position: 'before',
    decimalPlaces: 2,
  },
  pakistan: {
    code: 'PKR',
    symbol: 'Rs',
    name: 'Pakistani Rupee',
    locale: 'en-PK',
    position: 'before',
    decimalPlaces: 2,
  },
  bangladesh: {
    code: 'BDT',
    symbol: '৳',
    name: 'Bangladeshi Taka',
    locale: 'bn-BD',
    position: 'before',
    decimalPlaces: 2,
  },
  'sri lanka': {
    code: 'LKR',
    symbol: 'Rs',
    name: 'Sri Lankan Rupee',
    locale: 'en-LK',
    position: 'before',
    decimalPlaces: 2,
  },
  nepal: {
    code: 'NPR',
    symbol: 'Rs',
    name: 'Nepalese Rupee',
    locale: 'ne-NP',
    position: 'before',
    decimalPlaces: 2,
  },
  philippines: {
    code: 'PHP',
    symbol: '₱',
    name: 'Philippine Peso',
    locale: 'en-PH',
    position: 'before',
    decimalPlaces: 2,
  },
  malaysia: {
    code: 'MYR',
    symbol: 'RM',
    name: 'Malaysian Ringgit',
    locale: 'en-MY',
    position: 'before',
    decimalPlaces: 2,
  },
  singapore: {
    code: 'SGD',
    symbol: 'S$',
    name: 'Singapore Dollar',
    locale: 'en-SG',
    position: 'before',
    decimalPlaces: 2,
  },
  'hong kong': {
    code: 'HKD',
    symbol: 'HK$',
    name: 'Hong Kong Dollar',
    locale: 'en-HK',
    position: 'before',
    decimalPlaces: 2,
  },
  'united kingdom': {
    code: 'GBP',
    symbol: '£',
    name: 'British Pound',
    locale: 'en-GB',
    position: 'before',
    decimalPlaces: 2,
  },

  // ==================== FRENCH-SPEAKING COUNTRIES ====================
  // Europe
  france: {
    code: 'EUR',
    symbol: '€',
    name: 'Euro',
    locale: 'fr-FR',
    position: 'after',
    decimalPlaces: 2,
  },
  belgium: {
    code: 'EUR',
    symbol: '€',
    name: 'Euro',
    locale: 'fr-BE',
    position: 'after',
    decimalPlaces: 2,
  },
  switzerland: {
    code: 'CHF',
    symbol: 'CHF',
    name: 'Swiss Franc',
    locale: 'fr-CH',
    position: 'before',
    decimalPlaces: 2,
  },
  luxembourg: {
    code: 'EUR',
    symbol: '€',
    name: 'Euro',
    locale: 'fr-LU',
    position: 'after',
    decimalPlaces: 2,
  },
  monaco: {
    code: 'EUR',
    symbol: '€',
    name: 'Euro',
    locale: 'fr-MC',
    position: 'after',
    decimalPlaces: 2,
  },

  // Africa (Francophone)
  'côte d\'ivoire': {
    code: 'XOF',
    symbol: 'CFA',
    name: 'West African CFA Franc',
    locale: 'fr-CI',
    position: 'after',
    decimalPlaces: 2,
  },
  senegal: {
    code: 'XOF',
    symbol: 'CFA',
    name: 'West African CFA Franc',
    locale: 'fr-SN',
    position: 'after',
    decimalPlaces: 2,
  },
  cameroon: {
    code: 'XAF',
    symbol: 'FCFA',
    name: 'Central African CFA Franc',
    locale: 'fr-CM',
    position: 'after',
    decimalPlaces: 2,
  },
  'central african republic': {
    code: 'XAF',
    symbol: 'FCFA',
    name: 'Central African CFA Franc',
    locale: 'fr-CF',
    position: 'after',
    decimalPlaces: 2,
  },
  chad: {
    code: 'XAF',
    symbol: 'FCFA',
    name: 'Central African CFA Franc',
    locale: 'fr-TD',
    position: 'after',
    decimalPlaces: 2,
  },
  congo: {
    code: 'XAF',
    symbol: 'FCFA',
    name: 'Central African CFA Franc',
    locale: 'fr-CG',
    position: 'after',
    decimalPlaces: 2,
  },
  'equatorial guinea': {
    code: 'XAF',
    symbol: 'FCFA',
    name: 'Central African CFA Franc',
    locale: 'es-GQ',
    position: 'after',
    decimalPlaces: 2,
  },
  gabon: {
    code: 'XAF',
    symbol: 'FCFA',
    name: 'Central African CFA Franc',
    locale: 'fr-GA',
    position: 'after',
    decimalPlaces: 2,
  },
  benin: {
    code: 'XOF',
    symbol: 'CFA',
    name: 'West African CFA Franc',
    locale: 'fr-BJ',
    position: 'after',
    decimalPlaces: 2,
  },
  'burkina faso': {
    code: 'XOF',
    symbol: 'CFA',
    name: 'West African CFA Franc',
    locale: 'fr-BF',
    position: 'after',
    decimalPlaces: 2,
  },
  'guinea-bissau': {
    code: 'XOF',
    symbol: 'CFA',
    name: 'West African CFA Franc',
    locale: 'pt-GW',
    position: 'after',
    decimalPlaces: 2,
  },
  mali: {
    code: 'XOF',
    symbol: 'CFA',
    name: 'West African CFA Franc',
    locale: 'fr-ML',
    position: 'after',
    decimalPlaces: 2,
  },
  niger: {
    code: 'XOF',
    symbol: 'CFA',
    name: 'West African CFA Franc',
    locale: 'fr-NE',
    position: 'after',
    decimalPlaces: 2,
  },
  togo: {
    code: 'XOF',
    symbol: 'CFA',
    name: 'West African CFA Franc',
    locale: 'fr-TG',
    position: 'after',
    decimalPlaces: 2,
  },
  madagascar: {
    code: 'MGA',
    symbol: 'Ar',
    name: 'Malagasy Ariary',
    locale: 'fr-MG',
    position: 'after',
    decimalPlaces: 2,
  },
  djibouti: {
    code: 'DJF',
    symbol: 'Fdj',
    name: 'Djiboutian Franc',
    locale: 'fr-DJ',
    position: 'before',
    decimalPlaces: 2,
  },
  guinea: {
    code: 'GNF',
    symbol: 'FG',
    name: 'Guinean Franc',
    locale: 'fr-GN',
    position: 'after',
    decimalPlaces: 2,
  },
  mauritania: {
    code: 'MRU',
    symbol: 'UM',
    name: 'Mauritanian Ouguiya',
    locale: 'fr-MR',
    position: 'after',
    decimalPlaces: 2,
  },

  // Caribbean / North America (French-speaking)
  haiti: {
    code: 'HTG',
    symbol: 'G',
    name: 'Haitian Gourde',
    locale: 'fr-HT',
    position: 'before',
    decimalPlaces: 2,
  },
  martinique: {
    code: 'EUR',
    symbol: '€',
    name: 'Euro',
    locale: 'fr-MQ',
    position: 'after',
    decimalPlaces: 2,
  },
  guadeloupe: {
    code: 'EUR',
    symbol: '€',
    name: 'Euro',
    locale: 'fr-GP',
    position: 'after',
    decimalPlaces: 2,
  },
  'french guiana': {
    code: 'EUR',
    symbol: '€',
    name: 'Euro',
    locale: 'fr-GF',
    position: 'after',
    decimalPlaces: 2,
  },
  'french polynesia': {
    code: 'XPF',
    symbol: 'F',
    name: 'CFP Franc',
    locale: 'fr-PF',
    position: 'after',
    decimalPlaces: 2,
  },
  'new caledonia': {
    code: 'XPF',
    symbol: 'F',
    name: 'CFP Franc',
    locale: 'fr-NC',
    position: 'after',
    decimalPlaces: 2,
  },

  // ==================== SPANISH-SPEAKING COUNTRIES ====================
  // Europe
  spain: {
    code: 'EUR',
    symbol: '€',
    name: 'Euro',
    locale: 'es-ES',
    position: 'after',
    decimalPlaces: 2,
  },

  // South America
  argentina: {
    code: 'ARS',
    symbol: '$',
    name: 'Argentine Peso',
    locale: 'es-AR',
    position: 'before',
    decimalPlaces: 2,
  },
  bolivia: {
    code: 'BOB',
    symbol: 'Bs.',
    name: 'Bolivian Boliviano',
    locale: 'es-BO',
    position: 'before',
    decimalPlaces: 2,
  },
  chile: {
    code: 'CLP',
    symbol: '$',
    name: 'Chilean Peso',
    locale: 'es-CL',
    position: 'before',
    decimalPlaces: 2,
  },
  colombia: {
    code: 'COP',
    symbol: '$',
    name: 'Colombian Peso',
    locale: 'es-CO',
    position: 'before',
    decimalPlaces: 2,
  },
  peru: {
    code: 'PEN',
    symbol: 'S/',
    name: 'Peruvian Sol',
    locale: 'es-PE',
    position: 'before',
    decimalPlaces: 2,
  },
  uruguay: {
    code: 'UYU',
    symbol: '$U',
    name: 'Uruguayan Peso',
    locale: 'es-UY',
    position: 'before',
    decimalPlaces: 2,
  },
  paraguay: {
    code: 'PYG',
    symbol: '₲',
    name: 'Paraguayan Guarani',
    locale: 'es-PY',
    position: 'before',
    decimalPlaces: 2,
  },
  venezuela: {
    code: 'VES',
    symbol: 'Bs.',
    name: 'Venezuelan Bolívar',
    locale: 'es-VE',
    position: 'before',
    decimalPlaces: 2,
  },

  // Central America & Caribbean
  'costa rica': {
    code: 'CRC',
    symbol: '₡',
    name: 'Costa Rican Colón',
    locale: 'es-CR',
    position: 'before',
    decimalPlaces: 2,
  },
  guatemala: {
    code: 'GTQ',
    symbol: 'Q',
    name: 'Guatemalan Quetzal',
    locale: 'es-GT',
    position: 'before',
    decimalPlaces: 2,
  },
  honduras: {
    code: 'HNL',
    symbol: 'L',
    name: 'Honduran Lempira',
    locale: 'es-HN',
    position: 'before',
    decimalPlaces: 2,
  },
  nicaragua: {
    code: 'NIO',
    symbol: 'C$',
    name: 'Nicaraguan Córdoba',
    locale: 'es-NI',
    position: 'before',
    decimalPlaces: 2,
  },
  panama: {
    code: 'PAB',
    symbol: 'B/.',
    name: 'Panamanian Balboa',
    locale: 'es-PA',
    position: 'before',
    decimalPlaces: 2,
  },
  'dominican republic': {
    code: 'DOP',
    symbol: 'RD$',
    name: 'Dominican Peso',
    locale: 'es-DO',
    position: 'before',
    decimalPlaces: 2,
  },
  cuba: {
    code: 'CUP',
    symbol: '$',
    name: 'Cuban Peso',
    locale: 'es-CU',
    position: 'before',
    decimalPlaces: 2,
  },
  mexico: {
    code: 'MXN',
    symbol: '$',
    name: 'Mexican Peso',
    locale: 'es-MX',
    position: 'before',
    decimalPlaces: 2,
  },
  'el salvador': {
    code: 'USD',
    symbol: '$',
    name: 'US Dollar',
    locale: 'es-SV',
    position: 'before',
    decimalPlaces: 2,
  },
  ecuador: {
    code: 'USD',
    symbol: '$',
    name: 'US Dollar',
    locale: 'es-EC',
    position: 'before',
    decimalPlaces: 2,
  },

  // ==================== ADDITIONAL SUPPORTED COUNTRIES ====================
  // If your app supports any other countries, add them here
  netherlands: {
    code: 'EUR',
    symbol: '€',
    name: 'Euro',
    locale: 'nl-NL',
    position: 'after',
    decimalPlaces: 2,
  },
  germany: {
    code: 'EUR',
    symbol: '€',
    name: 'Euro',
    locale: 'de-DE',
    position: 'after',
    decimalPlaces: 2,
  },
  italy: {
    code: 'EUR',
    symbol: '€',
    name: 'Euro',
    locale: 'it-IT',
    position: 'after',
    decimalPlaces: 2,
  },
  portugal: {
    code: 'EUR',
    symbol: '€',
    name: 'Euro',
    locale: 'pt-PT',
    position: 'after',
    decimalPlaces: 2,
  },
};

// Helper to get default currency for a given language
export function getDefaultCurrencyForLanguage(lang: string): string {
  const map: Record<string, string> = {
    'en': 'USD',
    'en-GB': 'GBP',
    'en-US': 'USD',
    'fr': 'EUR',
    'fr-FR': 'EUR',
    'sw': 'KES',
    'sw-KE': 'KES',
    'es': 'EUR',
    'es-ES': 'EUR',
    'pt': 'EUR',
    'pt-PT': 'EUR',
  };
  return map[lang] || 'KES';
}